[appendix]
== Appendix: Bitcoin financial services

[[appdx01]]

This appendix describes the main financial services offered in the Bitcoin economy, comparing them to traditional financial services that are already familiar to consumers. It's not a list of sites or companies, as that would go stale immediately. Instead it is a list of service primitives with examples of existing implementations. For example, an escrow 
service would be described as an archetype, by analogy to a real-estate escrow, showing the unique characteristics, use case and need for escrow in the Bitcoin world. The escrow service archetype would be followed by two or three examples of well implemented actual escrow services, each demonstrating a capability unique to Bitcoin.

=== Currency Exchanges

=== Bitcoin market data services

=== Bitcoin ticker, order book, chart and analysis services

=== Peer-to-peer exchange

=== OTC and Web-of-Trust (WoT)

=== Escrow services

=== Monitoring services

=== Alert and notification services

=== Lending

=== P2P Lending

=== Securities

=== Mutual Funds

=== Angel investing

== Appendix: Bitcoin markets and applications

As above, this appendix describes services offered in the Bitcoin economy. Each service is described a a service archetype which is compared to a real-world example familiar to anyone. The description of such a service is followed by real-world examples that express 
these Bitcoin features. 

=== Currency transfer

=== US domestic

=== Other in-country 

=== International

=== Retail commerce

=== Physical (tangible) goods

=== Intangible products

=== Services

=== Technology services

=== Re-selling and Cross-selling

=== Wholesale commerce


== Appendix: Bitcoin Protocol Structure and Conventions

Reference index of main protocol primitives, packet structure, opcodes, state enumerations, protocol mechanics, time diagrams and protocol validation mechanisms. 


== Appendix: Bitcoin Transaction Script Operands and Tokens

More reference material as above


== Appendix: Bitcoin Cryptography Algorithms, Conventions and Conversions. 

More reference material as above


== Appendix: Bitcoin Meta-protocols: Mining Pool Protocols, Lightweight Client Protocols

More reference material as above
