[[ch00_intro_what_is_bitcoin]]
== Introduction

=== What is Bitcoin?

Bitcoin is digital money, a currency for and of the Internet. It is not owned or controlled by any company, group or country. It exists as a set of standards and reference software and as a running network with several thousand nodes worldwide. Behind the scenes, bitcoin is a network, a protocol, a standard and a currency. For now think of it simply as digital money that can be sent, received and stored by anyone, worldwide simply by downloading compatible software and joining a network. 


Under the hood, bitcoin is the culmination of decades of research in cryptography and distributed systems and represents four key innovations brought together in a unique and powerful combination. Bitcoin consists of a de-centralized peer-to-peer network, a public transaction ledger, a de-centralized mathematical and deterministic currency issuance, a de-centralized transaction verification system and a set of powerful APIs. All of these are "bitcoin", and each of these aspects of bitcoin will be examined in this book.

More than all of these parts, bitcoin is a digital economy platform, just like the Internet is a digital communications platform. With bitcoin, it is possible to build entire new financial systems, transaction types and economies on top of a purely digital, instantaneous and frictionless platform, an Internet for money.

==== A currency



==== A network and protocol

==== A distributed ledger

==== Proof of work and distributed issuance (mining)

==== A transaction language

==== An API

=== Getting Bitcoin

==== Obtaining the bitcoin software
==== bitcoin-qt, bitcoind
==== mobile client

=== History of bitcoin

==== A brief history of money
==== A brief history of crypto currencies
==== Public key cryptography and crypto-currency
==== Peer-to-Peer networks
=== The history of bitcoin
==== Why would I use bitcoin
===== As a merchant
===== As a consumer
===== As a developer, integrator
===== As an entrepreneur
===== As an investor