[[ch01_intro_what_is_bitcoin]]
== Introduction

=== What is Bitcoin?

Bitcoin is digital money that operates on the Internet, accessed through an application on a user's laptop or smartphone. Bitcoin currency units are stored in a digital "wallet" and transmitted instantly and securely from anyone to anyone, anywhere in the world. People can use bitcoin to purchase products or services, like a credit card, online or in person. It can be used to send money across borders, for remittances to family or international business. Bitcoins can be purchased and sold, exchanged for other currencies at a floating exchange rate, at specialized currency exchanges. Bitcoin in a sense is the perfect form of money for the Internet: fast, secure, borderless. 

Unlike traditional currencies, bitcoins are entirely virtual. There are no physical coins, or even digital coins. The coins are implied in transactions which transfer value from sender to recipient. Users of bitcoin own _keys_ which allow them to prove ownership of transactions in the bitcoin network, unlocking the value to spend it and transfer it to a new recipient. Those keys are stored in a digital wallet on each users computer. Possession of the key that unlocks a transaction is the only prerequisite to spend that bitcoin, putting the control entirely in the hands of each user. 

Bitcoins are created through a process called "mining", which involves looking for a solution to a difficult problem. Participants in the bitcoin network may operate as miners, using their computer's processing power to attempt to find solutions to this problem. Every 10 minutes on average, a new solution is found by someone who then is able to validate the transactions of the past 10 minutes and is rewarded with brand new bitcoins. Essentially, the currency-issuance function of a central bank is de-centralized and turned into a global competition. The rate at which new bitcoins are created is reduced by half every 4 years, resulting in an exponentially decreasing supply and a fixed total of 21 million coins. As a currency, bitcoin is deflationary and cannot be inflated by "printing" new money above and beyond the expected issuance rate. 

Behind the scenes, bitcoin is also the name of protocol, a network and a distributed computing innovation. The bitcoin currency is really only the first application of this invention. As a developer, I see bitcoin as akin to the Internet of money, a network for propagating value and securing the ownership of digital assets via distributed computation. There's a lot more to bitcoin than first meets the eye. 

In this chapter we'll get started with bitcoin by explaining some of the main concepts and terms, getting the necessary software and using bitcoin for simple transactions. In following chapters we'll start unwrapping the layers of technology that make bitcoin possible and examine the inner workings of the bitcoin network and protocol. 

=== History of Bitcoin

Bitcoin is the culmination of decades of research in cryptography and distributed systems and represents four key innovations brought together in a unique and powerful combination. Bitcoin consists of a de-centralized peer-to-peer network, a public transaction ledger, a de-centralized mathematical and deterministic currency issuance, a de-centralized transaction verification system and a set of powerful APIs.

Bitcoin was invented in 2008 by Satoshi Nakamoto with the publication of a paper titled "Bitcoin: A Peer-to-Peer Electronic Cash System". Satoshi Nakamoto combined several prior inventions such as b-money and HashCash to create a completely de-centralized electronic cash system that does not rely on a central authority for settlement and validation of transactions. The key innovation was to use a Proof-Of-Work algorithm to conduct a global election every 10 minutes, allowing the de-centralized network to arrive at _consensus_ about the state of transactions. This elegantly solves the issue of double-spend, a weakness of digital money, where a single currency unit can be spent twice.

Satoshi Nakamoto's invention is also a practical solution to a previously unsolved problem in distributed computing, known as the Byzantine Generals problem. As such, it represents a breakthrough in distributed computing science and has wide applicability beyond currency. It can be used to achieve consensus on decentralized networks for provably-fair elections, lotteries, asset registries, digital notarization and more. 

Satoshi Nakamoto withdrew from the public in April of 2011, leaving the responsibility of developing the code and network to a thriving group of volunteers. The name Satoshi Nakamoto is an alias and the identity of the person or people behind this invention is currently unknown. However, neither Satoshi Nakamoto nor anyone else exerts control over the bitcoin system, which operates based on mathematical principles. The invention itself is groundbreaking and has already spawned new science in the fields of distributed computing, economics and econometrics. 

The bitcoin network started in 2009, based on a reference implementation published by Nakamoto and since revised by many other programmers. During the first four years of operation, the network has grown to include an enormous amount of Proof-Of-Work computation, thereby increasing in security and resillience. As the network has grown, the exchange rate of a bitcoin has also grown dramatically and with quite a lot of volatility. In 2013, the total market value of bitcoin's primary monetary supply measure (M0) is estimated at more than 10 billion US dollars. The largest transaction processed by the network was a staggering $150 million US dollars, transmitted instantly and processed without any fees.

=== Bitcoin Uses, Users and Their Stories

Bitcoin is a technology, but it expresses money which is fundamentally a language for exchanging value between people. Let's look at the people who are using bitcoin and some of the most common uses of bitcoin through their stories. We will re-use these stories throughout the book to illustrate the real-life uses of bitcoin and how they are made possible by the various technologies that are part of bitcoin. 

North American Retail::
Alice lives in Northern California, in the Bay Area. She has heard about bitcoin from her techie friends and wants to start using it. We will follow her story as she tries to spend her bitcoin on a cup of coffee at Bob's Cafe in Palo Alto.

Offshore Contract Services::
Bob, the cafe owner in Palo Alto is building a new website. He has contracted with an Indian web developer, Gopesh, who lives in Bangalore India. Gopesh has agreed to be paid in bitcoin. 

Charitable Donations::
Eugenia is the director of a children's charity in the Philippines. Recently she has discovered bitcoin and wants to use it to reach a whole new group of foreign and domestic donors to fundraise for his charity. She's also investigating ways to use bitcoin to distribute funds quickly to areas of need. 

Remitances and Reverse Remitances::
Gopesh, the Indian web developer, is supporting his daughter Radhika who is a student in Essex, England. Gopesh is now considering sending Radhika bitcoin to reduce the fees he pays to wire transfer companies and banks.

Import/Export::
Mohammed is an electronics importer in Dubai. He's trying to use bitcoin to buy electronics from the USA and China for import into the U.A.E., to accelerate the process of financing inventory which is very slow. 

Mining for Bitcoin::
Jing is an engineering student in Shanghai. He has built a "mining" rig to mine for bitcoins, using his engineering skills to supplement his income. 

Peer Lending::
Zenab is a shopkeeper in Kisumu, Kenya and needs a loan to buy new inventory for her shop. With the assistance of a micro-lending organization, she is financing a micro-loan in bitcoin from individual lenders all across the world.

Each of the stories above is based on real people and real industries that are currently looking to bitcoin to create new opportunities. 

=== Getting Started

To join the bitcoin network and start using the currency, all a user has to do is download an application. Since bitcoin is a standard, there are many implementations of the bitcoin client software. There is also a "reference implementation", also known as the Satoshi Client, which is managed by a team of developers and is derived from the original implementation written by Satoshi Nakamoto. 

You can download the Satoshi Client from bitcoin.org. Depending on your operating system, it will be called bitcoin-qt or bitcoind. 

The bitcoin client is not just an interface into the bitcoin network, it also contains complete implementations of a wallet, a miner and a transaction validation engine that can independently validate any transaction. The client can operate as a full node on the network, bringing the power of a bank onto your laptop or smartphone. With the full client you can store keys, create and validate complex transactions and interact with the network at the same level as any other node. You become a bitcoin banker, as much as a bitcoin user. 

