[[ch05_entrepreneurs]]
== Chapter 5 - Bitcoin for entrepreneurs

This chapter is presented from the perspective of entrepreneurs who wish to venture in the bitcoin economy. The main focus is on understanding the particular challenges, but also opportunities, introduced by a bitcoin venture vis-a-vis a more traditional software or technology startup. A few different case studies will be referenced from the beginning of the chapter, with detail added as new concepts are introduced. The case studies will be based on existing, successful and long running bitcoin businesses in the US and abroad. 

=== Risk and uncertainty
=== Political and regulatory risk
=== The reputation of early use patterns
=== Dealing with "legacy" banking
=== Friction on the bitcoin on/off ramps
=== Bitcoin accounting and book-keeping
=== Bitcoin payroll
=== Bitcoin angel investors and investment clubs
=== Bitcoin securities listings (going bitcoin IPO)
=== Crowdfunding for bitcoin
=== Bitcoin source, licensing and intellectual property
=== Bitcoin trademarks
=== Bitcoin patent base
=== Bitcoin business community resources
