[[ch9]]
== Alternative chains, currencies and applications

Bitcoin was neither the beginning nor the end of the digital currency evolution. It came from twenty years of research in distributed systems and currencies and brought a revolutionary new technology into the space: the de-centralized consensus mechanism based on Proof-of-Work. The invention at the heart of bitcoin has ushered a wave of innovation in currencies, financial services, economics, distributed systems, voting systems, corporate governance and contracts. 

In this chapter we'll examine the many offshoots of the bitcoin and blockchain inventions, the alternative chains, currencies and applications built since the introduction of this technology in 2009. 

[[alt_taxonomy]]
=== A taxonomy of blockchain innovation

Bitcoin is a mashup of four important innovations: a de-centralized ledger, a consensus mechanism based on proof-of-work, a currency based on algorithmic macro-economics, and a transaction script-based language. Each of these innovations has spawned dozens of variations, mashups, forks, imitators and clones. To help us study these bitcoin alternatives and variants, we will categorize them by looking at their differentiation in the four core technologies: 

* Alternative chains
* Alternative consensus systems
* Alternative currency systems (Alt-coins)
* Alternative transactional systems

In addition to the systems that differ from bitcoin in these four core areas, we will also look at protocol layers, platforms or "apps" built on top of bitcoin itself:

* Meta Coins 
* Blockchain "Apps"
* Blockchain Extended Protocols/Platforms

=== Alt-Coins - Forking the Bitcoin Code

The most common variants of bitcoin are alternative currencies commonly called _alt-coins_. Alt-coins first emerged in 2011, when Charles Lee created _Litecoin_, a cyrpto-currency based on bitcoin's source code but with several key differences and operating on a separate blockchain. Litecoin is promoted as "silver to bitcoin's gold" and intended to offer a "lighter" alternative to bitcoin. Litecoin differs from bitcoin in two key areas:

* Proof-of-Work: Litecoin uses the memory-intensive algorithm _scrypt_ instead of SHA256 as its PoW algorithm. This makes Litecoin less amenable to ASIC mining and therefore more CPU/GPU "friendly". The intent is to avoid centralization of mining and allow mining with broadly-available consumer hardware such as Graphics Processing Units (GPUs)

* Block Target Time: Litecoin generates blocks every 2.5 minutes, for faster confirmation times. Other currency issuance parameters (halving and difficulty re-targetting) are the same as bitcoin which results in four times more total currency units (84 million).

Since the inauguration of the alt-coin space with Litecoin, several hundred other alt-coins have been issued. Some are merely copycats of bitcoin, with minimal differences or even just a name change. Others incorporate significant changes to appeal to some niche application, market, audience or use. 

In the next few sections we will highlight some alt-coins that best represent different approaches and innovations. The example coins chosen below are not contenders to replace bitcoin and are not even necessarily coins that will succeed in the long run, but they exemplify certain interesting characteristics that make them notable.

* 











