[preface]
=== Quick Glossary

This quick glossary contains many of the terms used in relation to bitcoin. These terms are used throughout the book, so bookmark this for a quick reference and clarification.

address::
((("bitcoin address")))
((("address", see="bitcoin address")))
((("public key", see="bitcoin address")))
    A bitcoin address looks like +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+. It consists of a string of letters and numbers starting with a "1" (number one). Just like you ask others to send an email to your email address, you would ask others to send you bitcoin to your bitcoin address.

bip::
((("bip"))) 
    Bitcoin Improvement Proposals.  A set of proposals that members of the bitcoin community have submitted to improve bitcoin.  For example, BIP0021 is a proposal to improve the bitcoin URI scheme.

bitcoin::
((("bitcoin"))) 
    The name of the currency unit (the coin), the network, and the software.

block::
((("block")))
    A grouping of transactions, marked with a timestamp, and a fingerprint of the previous block. The block header is hashed to find a Proof-Of-Work, thereby validating the transactions. Valid blocks are added to the main blockchain by network consensus.

blockchain::
((("blockchain")))
		A list of validated blocks, each linking to its predecessor all the way to the genesis block.
	
confirmations::
((("confirmations")))
		Once a transaction is included in a block, it has "one confirmation." As soon as _another_ block is mined on the same blockchain, the transaction has two confirmations, etc. Six or more confirmations is considered sufficient proof that a transaction cannot be reversed.

difficulty::
((("difficulty")))
	A network-wide setting that controls how much computation is required to find a Proof-Of-Work.

difficulty target::
((("target difficulty")))
 	A difficulty at which all the computation in the network will find blocks approximately every 10 minutes.

difficulty re-targeting::
((("difficulty re-targeting")))
	A network-wide recalculation of the difficulty that occurs once every 2,106 blocks and considers the hashing power of the previous 2,106 blocks.
	
fees::
((("fees")))
	The sender of a transaction often includes a fee to the network for processing the requested transaction.  Most transactions require a minimum fee of 0.5mBTC.

hash::
((("hash")))
	A digital fingerprint of some binary input.

genesis block::
((("genesis block")))
	The first block in the blockchain, used to initialize the crypto-currency.
	
miner::
((("miner")))
	A network node that finds valid Proof-Of-Work for new blocks, by repeated hashing.

network::
((("network")))
	A peer-to-peer network that propagates transactions and blocks to every bitcoin node on the network. 
	
Proof-Of-Work::
((("proof-of-work")))
	A piece of data that requires significant computation to find. In bitcoin, miners must find a numeric solution to the SHA256 algorithm that meets a network-wide target, the difficulty target. 

reward::
((("reward")))
	An amount included in each new block as a reward by the network to the miner who found the Proof-Of-Work solution. It is currently 25BTC per block.

secret key (aka private key)::
((("secret key")))
((("private key", see="secret key")))
	The secret number that unlocks bitcoins sent to the corresponding address.  A secret key looks like +5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh+.
	
transaction::
((("transaction")))
	In simple terms, a transfer of bitcoins from one address to another. More precisely, a transaction is a signed data structure expressing a transfer of value. Transactions are transmitted over the bitcoin network, collected by miners, and included into blocks, made permanent on the blockchain.

wallet::
((("wallet"))) 
	Software that holds all your bitcoin addresses and secret keys. Use it to send, receive, and store your bitcoin.