["dedication", role="praise"]
== Praise for 'Test-Driven Development with Python'

[quote, Gavin Andresen, Chief Scientist Bitcoin Foundation]
____
“When I talk about bitcoin to general audiences, I am sometimes asked 'but how does it really work?' Now I have a great answer for that question, because anybody who reads _Mastering Bitcoin_ will have a deep understanding of how it works and will be well-equipped to write the next generation of amazing cryptocurrency applications.”
____

[quote, Naval Ravikant, Cofounder AngelList]
____
“Bitcoin and blockchain technologies are becoming fundamental building blocks for the next generation internet. Silicon Valley's best and brightest are working on it. Andreas' book will help you join the software revolution in the world of finance.” 
____

[quote, Balaji S. Srinivasan (@balajis), General Partner, Andreessen Horowitz]
____
“_Mastering Bitcoin_ is the best technical reference available on bitcoin today. And bitcoin is likely to be seen in retrospect as the most important technology of this decade. As such, this book is an absolute must-have for any developer, especially those interested in building applications with the bitcoin protocol. Highly recommended.”
____