////


Will be merged later into chapter 6 or 7, as the book is reorganized


////
[[state_channels]]
=== State Channels

_State channels_, or _payment channels_ are a system of smart-contract based virtual channels that enable payments to be exchanged between two parties that do not need to trust each other, with settlement via transactions on the blockchain. 

In the simplest form, a state channel is made by constructing a sequence of time-locked transactions with incrementing value. This is a one-way state channel between two parties. A one-way channel like this is useful for making off-chain micro-payments in return for delivery of a metered service, such as streamed video or Wifi service. 

More complex state channels can be used to build bi-directional off-chain payments between two parties. These are useful for maintaining a running balance between two parties without having to commit transactions to the bitcoin blockchain. 

Finally, state channels can be linked together to form a routed multi-hop network of payments between multiple parties. Such a network can support a much higher volume of transactions, each of very small value (micro-payments), for much lower cost than the equivalent transactions on the bitcoin blockchain. Yet, the trust is entirely 

